### ISSUE TITLE
怎么去使用的    也要建立实体类吗？  

### ISSUE THREAD

**Issue by szGH** [alukaa/swoft-mongo-pool#2]
怎么去使用的    也要建立实体类吗？

**Comment by szGH** [comment]
可以使用composer安装吗？

**Comment by alukaa** [comment]
等我更新到composer,哈哈

**Comment by szGH** [comment]
怎么去调用啊  你的不是ext-mongodb这个包吗？

**Comment by szGH** [comment]
我使用new的方式 提示找不到app\MongoDB\mongo这个类

**Comment by alukaa** [comment]
不好意思才看到，我用的bean进行的初始化，明天上午来交流交流

**Comment by alukaa** [comment]
话说应该是App吧，没有nampspace没对哦

**Comment by alukaa** [comment]
复制到app/Lib下面就可以使用了

**Comment by alukaa** [comment]
@szGH 已经更新到composer,用法见readme,希望能帮到你

**Comment by szGH** [comment]
我按照你的教程来了  调用  提示  Class 'SwoftMongo\\MongoDB\\Mongo' not found   我的swoft中使用composer 下载不了   我是下载zip  解压到vend目录下的  然后  mongo.php  就是复制你的那个  就是改了mongo的用户名  密码  数据库名称    头部  我使用的use SwoftMongo\MongoDB\Mongo;   方法中使用
 $data   =   Mongo::fetchAll('miyuan_orders_main');  提示找不到类

**Comment by alukaa** [comment]
额，我的问题，晚上回去看看修改下，psr4的问题

**Comment by szGH** [comment]
好的  谢谢了

**Comment by alukaa** [comment]
@szGH 你执行下```composer dumpautoload -o```试试？

**Comment by alukaa** [comment]
直接下载复制比```composer install ```少了一个```dump file ```的过程

**Comment by szGH** [comment]
使用composer dumpautoload -o好像也是不行  swoft框架中使用这个命令 也只是提示了  Generating optimized autoload files  就没有  好像是我的composer没法用的

**Comment by szGH** [comment]
https://user-images.githubusercontent.com/34707942/47906069-6c31eb80-dec3-11e8-81a9-bed1119a8cb2.png

**Comment by alukaa** [comment]
@szGH 不好意思最近有点忙，一直没修复这个问题，请更新版本到v1.1
```
composer update
```
修复了这个问题

**Comment by alukaa** [comment]
另外你的composer 使用不了，请换国内镜像
```
"repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.laravel-china.org"
        }
    }
```

**Comment by szGH** [comment]
![image](https://user-images.githubusercontent.com/34707942/48543423-75c44600-e8fc-11e8-831a-1ab993b4e47a.png)
我这里使用的是国内的镜像把

**Comment by alukaa** [comment]
查看/vendor/composer/autoload_psr4.php文件有没有dump ```SwoftMongo``` namespae

**Comment by alukaa** [comment]
这不是一个标准的psr4文件结构，自动psr4加载是找不到的，也并没有include file,必须dump

**Comment by alukaa** [comment]
或者你改成你想要的也可以

**Comment by szGH** [comment]
![image](https://user-images.githubusercontent.com/34707942/48543986-a48eec00-e8fd-11e8-965c-24f2bda9a52a.png)
这个不需要是吗？   按照你上面的添加  然后composer dumpautoload -o是吗

**Comment by alukaa** [comment]
这个是swoft本身的文件，与这个本身无关

**Comment by alukaa** [comment]
![image](https://user-images.githubusercontent.com/8164389/48544443-91305080-e8fe-11e8-8729-f4e6d90dc683.png)
![image](https://user-images.githubusercontent.com/8164389/48544459-97263180-e8fe-11e8-8867-f78d1208c8b9.png)
![image](https://user-images.githubusercontent.com/8164389/48544500-adcc8880-e8fe-11e8-8b69-7bf5301a3653.png)
你要明白composer的工作机制，不是复制进去就一定可以工作的

**Comment by szGH** [comment]
就是   swoft我需要新下载一个是吗？

**Comment by alukaa** [comment]
不是，很简单的问题变复杂了。这个包本来就是依赖swoft框架的，只有在swoft框架中才能运行，没有重新下载这一说，本来composer.json里面也是申明了依赖的

**Comment by alukaa** [comment]
关键在于你dump过后composer有没有加入这个包的namespace，这才是class not found的关键

**Comment by szGH** [comment]
![image](https://user-images.githubusercontent.com/34707942/48544845-77dbd400-e8ff-11e8-8758-d93ed11715f7.png)
这个是执行dump的那个结果返回

**Comment by alukaa** [comment]
不是,你需要查看的是/vendor/composer/autoload_psr4.php这个文件，里面到底是些什么东西，截个图我看看？

**Comment by szGH** [comment]
return array(
    'phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/type-resolver/src'),
    'Zend\\Stdlib\\' => array($vendorDir . '/zendframework/zend-stdlib/src'),
    'Zend\\Mime\\' => array($vendorDir . '/zendframework/zend-mime/src'),
    'XdgBaseDir\\' => array($vendorDir . '/dnoegel/php-xdg-base-dir/src'),
    'Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'Symfony\\Polyfill\\Php70\\' => array($vendorDir . '/symfony/polyfill-php70'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\VarDumper\\' => array($vendorDir . '/symfony/var-dumper'),
    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Symfony\\Component\\Stopwatch\\' => array($vendorDir . '/symfony/stopwatch'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\OptionsResolver\\' => array($vendorDir . '/symfony/options-resolver'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Swoft\\WebSocket\\Server\\' => array($vendorDir . '/swoft/websocket-server/src'),
    'Swoft\\View\\' => array($vendorDir . '/swoft/view/src'),
    'Swoft\\Test\\' => array($baseDir . '/test'),
    'Swoft\\Task\\' => array($vendorDir . '/swoft/task/src'),
    'Swoft\\Sg\\' => array($vendorDir . '/swoft/service-governance/src'),
    'Swoft\\Session\\' => array($vendorDir . '/swoft/session/src'),
    'Swoft\\Rpc\\Server\\' => array($vendorDir . '/swoft/rpc-server/src'),
    'Swoft\\Rpc\\Client\\' => array($vendorDir . '/swoft/rpc-client/src'),
    'Swoft\\Rpc\\' => array($vendorDir . '/swoft/rpc/src'),
    'Swoft\\Redis\\' => array($vendorDir . '/swoft/redis/src'),
    'Swoft\\Process\\' => array($vendorDir . '/swoft/process/src'),
    'Swoft\\Memory\\' => array($vendorDir . '/swoft/memory/src'),
    'Swoft\\I18n\\' => array($vendorDir . '/swoft/i18n/src'),
    'Swoft\\Http\\Server\\' => array($vendorDir . '/swoft/http-server/src'),
    'Swoft\\Http\\Message\\' => array($vendorDir . '/swoft/http-message/src'),
    'Swoft\\HttpClient\\' => array($vendorDir . '/swoft/http-client/src'),
    'Swoft\\Devtool\\' => array($vendorDir . '/swoft/devtool/src'),
    'Swoft\\Db\\' => array($vendorDir . '/swoft/db/src'),
    'Swoft\\DataParser\\' => array($vendorDir . '/swoft/data-parser/src'),
    'Swoft\\Console\\' => array($vendorDir . '/swoft/console/src'),
    'Swoft\\Cache\\' => array($vendorDir . '/swoft/cache/src'),
    'Swoft\\' => array($vendorDir . '/swoft/framework/src'),
    'Seld\\PharUtils\\' => array($vendorDir . '/seld/phar-utils/src'),
    'Psy\\' => array($vendorDir . '/psy/psysh/src'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Server\\' => array($vendorDir . '/psr/http-server-handler/src', $vendorDir . '/psr/http-server-middleware/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PhpDocReader\\' => array($vendorDir . '/php-di/phpdoc-reader/src/PhpDocReader'),
    'PhpCsFixer\\' => array($vendorDir . '/friendsofphp/php-cs-fixer/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Leuffen\\TextTemplate\\' => array($vendorDir . '/text/template/src'),
    'JakubOnderka\\PhpConsoleHighlighter\\' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor\\' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'Dotenv\\' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'Composer\\XdebugHandler\\' => array($vendorDir . '/composer/xdebug-handler/src'),
    'Composer\\Semver\\' => array($vendorDir . '/composer/semver/src'),
    'App\\' => array($baseDir . '/app'),
    '' => array($vendorDir . '/nesbot/carbon/src'),
);

**Comment by szGH** [comment]
方便给个qq吗 加你qq请教你下咯

**Comment by alukaa** [comment]
1033210915

**Comment by alukaa** [comment]
加进去后执行```composer dumpautoload -o```
![image](https://user-images.githubusercontent.com/8164389/48592732-c1bacd80-e984-11e8-8477-826099ed148e.png)

**Comment by alukaa** [comment]
现在可以正常使用了
